name: buga-cicdtest
version: '1.0.0'
summary: CI-CD with snap
description:  A test to check out CICD with snaps
grade: stable
confinement: strict

apps:
  hello:
    command: bin/hello
  java:
    command: java

parts:
  gnu-hello:
    plugin: maven
    source: https://github.com/swapneeldatta/cicd-poc.git
    stage-packages: [ openjdk-8-jre, ca-certificates-java, maven]

